name: Debug pakai sshx.io + kirim Discord

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sshx
        run: curl -fsSL https://sshx.io/get | sh

      - name: Start sshx session
        id: sshx
        run: |
          echo "🔥 Membuat session sshx..."
          URL=$(sshx --share | grep -Eo 'https://sshx.io/[a-zA-Z0-9]+')
          echo "🔗 SSHX URL: $URL"
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Kirim link ke Discord
        if: ${{ steps.sshx.outputs.url != '' }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🖥️ **SSHX Session Aktif!**\n${{ steps.sshx.outputs.url }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Keep alive
        run: sleep infinity
