name: Tmate Debug Fixed

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Test connection to tmate.io
        run: ping -c 3 tmate.io || echo "Ping failed, tapi lanjut coba"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Keep alive
        run: sleep infinity
